server:
  port: 8080

spring:
  profiles:
    active:
    - dev  
  mvc:
    servlet:
      load-on-startup: 1
  cache:
    type: redis ## jcache
    redis:
      cache-null-values: false
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: H2
  h2:
    console:
      enabled: true

application:
  cache:
  - cache-name: usersCache ## Cache name
    ttl: 300 ## In seconds
